### PR TITLE
Fix paths for Windows arm64 build

### PR DESCRIPTION
**Pull request by theKidOfArcrania**
Fixes issue #604 by using `Path::join` to denote a subpath (as opposed to using forward slash).

### CODE REVIEW

**Comment by theKidOfArcrania** [comment]
Wanted to see if we can get an aarch64 windows build as part of the CI/CD, but it seems like this is something that is not supported properly? Or is there a way and I'm just not familiar with it?

**Comment by Amanieu** [comment]
Github doesn't have any ARM64 Windows runners, so it's fine to just exclude this from CI.

**Comment by theKidOfArcrania** [comment]
Alright, this bug *should* be fixed, I've tried building windows aarch64 by passing an unc path to `--target-dir` and it no longer crashes. Though I've taken a comb through the code, and we might have deeper issues if let's say the `RUST_COMPILER_RT_ROOT` is an unc path, since there are a lot of paths relative to that directory that contain forward slashes. It may also be harder to fix those issues also.

Normally this shouldn't be the case, but in case if this comes up, there may be larger fixes needed.

**Comment by tgross35** [comment]
You could do a cross compile build or at least check on an x64 windows runner to verify the config without running tests

**Pull request merged**
