### PR TITLE
Add compiler-rt fallbacks on loongarch64-musl

### PR DESCRIPTION
**Pull request by heiher**

### CODE REVIEW

**Comment by heiher** [comment]
cc @Amanieu It seems that the CI failure is not related to this PR.

**Comment by heiher** [comment]
Note: @Amanieu: This PR is currently blocked on [#121552](https://github.com/rust-lang/rust/issues/121552).

**Comment by Amanieu** [comment]
CI should be fixed now, can you rebase?

**Comment by heiher** [comment]
> CI should be fixed now, can you rebase?

Rebase is done, Thanks.

**Pull request merged**
