### PR TITLE
Partial float refactor

### PR DESCRIPTION
**Pull request by AaronKutch**
This refactors the more troublesome parts of the floating point folder, adds more tests, removes the old test system, and fixes all clippy warnings. Fixes issues #395, #197, #162, #168. Issues #75 and #154 should also be closed.

### CODE REVIEW

**Comment by AaronKutch** [comment]
I want to see this merged, but the PRs newer than this one that are currently open should be merged first

**Comment by Amanieu** [comment]
Can you rebase?

**Comment by AaronKutch** [comment]
I got everything to work except for adding clippy to the CI. Issue https://github.com/rust-lang/rustup/issues/1501 doesn't look like it was resolved.

**Comment by Amanieu** [comment]
Can you try applying the workaround suggest by @RalfJung for clippy?

**Comment by AaronKutch** [comment]
Sorry if I spammed anyone's inbox, GHA always gives me trouble with environment variables. Anyway, I think `compiler-builtins` is now not just a heap of hacks, but an orderly and well tested heap of hacks.

**Pull request merged**
