### PR TITLE
Add `__powitf2` symbol for `f128` integer exponentiation

### PR DESCRIPTION
**Pull request by tgross35**

### CODE REVIEW

**Comment by tgross35** [comment]
Blocked until we have the function in libs, https://github.com/rust-lang/rust/pull/125188

**Review by Qadeem411 — APPROVED** [review]

**Comment by tgross35** [comment]
Lol @Qadeem411 I have to imagine you didn’t mean to approve this

**Comment by tgross35** [comment]
WIndows targets appear to fail compiling this crate because powi uses the f128 multiply and divide in its implementation, and these are not available. I don't know why only Windows has the issue, but other platforms without these available natively (e.g. aarch darwin) do not, must be slightly different linkage rules. How should I handle this @Amanieu?

**Comment by Amanieu** [comment]
I think this just happens to work before libgcc provides these symbols, but that's not available on -msvc targets. You'll need to implement a fallback for that target for testing, at least temporarily.

**Comment by tgross35** [comment]
It looks like I can make this work by recreating `__multf3` and `__divtf3` in testcrate's `lib.rs`, this will just be blocked until I implement `divtf3`.

**Comment by tgross35** [comment]
`__divtf3` hasn't made it to nightly yet, and I can't seem to figure out a way to provide it here to avoid the Windows linking. Hopefully that won't be too far off, but I just disabled this new symbol on MSVC in the meantime.

This should be ready for a look when you get the chance @Amanieu

**Review by Amanieu — APPROVED** [review]
LGTM. Feel free to merge it either now (and enable it with MSVC later) or after a boostrap bump.

**Comment by tgross35** [comment]
Thanks! https://github.com/rust-lang/rust/pull/130792 hasn't been picked up yet so I might as well just update that to include this.

**Pull request merged**
