### PR TITLE
avoid the core_intrinsics feature (for a transition)

### PR DESCRIPTION
**Pull request by RalfJung**
This should let us do the transition in https://github.com/rust-lang/rust/pull/118123.

### CODE REVIEW

**Comment by Nilstrieb** [comment]
maybe its easier to just special case core_intrinsics in rustc instead of renaming

**Comment by RalfJung** [comment]
That is an option, but hard-coding a lib feature name in the compiler did not seem great...

**Comment by Nilstrieb** [comment]
🤷 it seems easier than all of this nightmare stuff, and like, I don't think it will change or cause significant trouble to hardcode it, intrinsics are very entangled anyways

**Comment by RalfJung** [comment]
You are probably right, I'm just too much of a perfectionist. :see_no_evil:

**Comment by RalfJung** [comment]
All right, trying to do this without a rename now.

**Pull request closed without merging**
