### PR TITLE
Add generic unorddf2vfp() and unordsf2vfp()

### PR DESCRIPTION
**Pull request by sbechet**
A (weak) contribution to trying to understand this great project.

### CODE REVIEW

**Comment by Amanieu** [comment]
Since these only exist on ARM, please mark them with `#[cfg(target_arch = "arm")]`.

**Comment by sbechet** [comment]
> Since these only exist on ARM, please mark them with `#[cfg(target_arch = "arm")]`.

You right. I will correct that. Before I submit an update are we ok about check boxes. I ask the question because I saw that certain boxes were not checked for certain functions even though the generic version of the code exists.

**Comment by Amanieu** [comment]
I double-checked the *vfp functions and it turns out that they are only used on old versions of 32-bit iOS with ARMv5. Since we don't support this in any current target, we can probably just remove all the *vfp functions.

**Comment by sbechet** [comment]
That's perfect, in this case, I can close this pull request without further delay.
Are you interested in a pull request to update the README and deprecate all these functions or will you do it? There must not be much left to do in this project I imagine?

**Comment by Amanieu** [comment]
Yes, I would be interested in a PR to update the README and remove all the existing *vfp functions since they serve no purpose.

**Comment by tgross35** [comment]
@sbechet since we probably don't need this change as-is I am just going to close this PR. Feel free to create a new one that removes the symbols as mentioned above.

**Pull request closed without merging**
