### PR TITLE
Add lgamma_r and lgammaf_r

### PR DESCRIPTION
**Pull request by ankane**
For https://github.com/rust-lang/rust/issues/99842#issuecomment-1454900224

Similar to #482

### CODE REVIEW

**Comment by ankane** [comment]
Note the signature [is different](https://linux.die.net/man/3/lgamma_r) from `math.h` - not exactly sure if that should be taken into account here or downstream for https://github.com/rust-lang/rust/pull/99747.

**Comment by ankane** [comment]
Now thinking it may need to be taken into account here since the signature in [cmath.rs](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/cmath.rs) will be:

```rust
pub fn lgamma_r(n: f64, s: &mut i32) -> f64;
```

**Comment by Amanieu** [comment]
The signature here should match the C one. You'll need to manually generate the wrapper function instead of using the `no_mangle` macro.

**Comment by ankane** [comment]
Thanks (again) @Amanieu. Updated to match the C signature.

**Comment by ankane** [comment]
Thanks!

**Pull request merged**
