### PR TITLE
Add tgamma and tgammaf

### PR DESCRIPTION
**Pull request by ankane**
For https://github.com/rust-lang/rust/pull/99747

### CODE REVIEW

**Comment by ankane** [comment]
Not sure I fully understand the failure, but guessing it may be due to `tgamma` and `tgammaf` not having this line in `libm`:

```rust
#[cfg_attr(all(test, assert_no_panic), no_panic::no_panic)]
```

**Comment by Amanieu** [comment]
I believe the issue that is this line in `tgamma.rs`:
```rust
n = (n + 1) / 2;
```

In debug builds this introduces a call to panic because we still emit a check against division by zero. This can be fixed by using the `div!` macro defined in `libm/src/math/mod.rs`.

**Comment by ankane** [comment]
Thanks @Amanieu! I updated the call in [this branch](https://github.com/rust-lang/libm/compare/master...ankane:libm:tgamma_no_panic). It looks like there may be another panic.

```sh
env RUSTFLAGS='-Ccodegen-units=1' cargo test --all --release --features 'unstable musl-reference-tests'
```

(on Ubuntu 20.04) gives:

```text
libm.458c1a1f-cgu.0:(.text._ZN4core3ptr58drop_in_place$LT$libm..math..tgamma..tgamma..__NoPanic$GT$17ha3e84c801b2d4a51E+0x3): undefined reference to `

ERROR[no-panic]: detected panic in function `tgamma`
'
/usr/bin/ld: /home/vagrant/libm/target/release/deps/libm-dddd41468bd528f3.libm.458c1a1f-cgu.0.rcgu.o: in function `core::ptr::drop_in_place<libm::math::tgammaf::tgammaf::__NoPanic>':
libm.458c1a1f-cgu.0:(.text._ZN4core3ptr60drop_in_place$LT$libm..math..tgammaf..tgammaf..__NoPanic$GT$17h69ee5eb5a9c950f0E+0x3): undefined reference to `

ERROR[no-panic]: detected panic in function `tgammaf`
'
collect2: error: ld returned 1 exit status
```

Will try to track it down, but please let me know if you have any ideas.

**Comment by ankane** [comment]
Looks like it was indexing. Replaced with `i!` macro, and will submit a PR to `libm`. Thanks again for the help!

**Comment by Amanieu** [comment]
I've merged the libm PR, you can update the submodule in this PR.

**Comment by ankane** [comment]
Great, thanks! Looks like it fixed the test suite.

**Comment by Amanieu** [comment]
I published a new version of the crate, you can now make PR to rust-lang/rust to update it there.

**Comment by ankane** [comment]
Perfect, I appreciate all the help (first time contributing to Rust).

**Pull request merged**
